name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@f24d7193d98baebaeacc7e2227925dd47cc267f5 # v4.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-provider-cofide-gh-actions-access
          role-session-name: terraform-provider-cofide-gh-actions-access
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Import GPG key
        run: |
          GPG_FINGERPRINT_SECRET_ARN="arn:aws:secretsmanager:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:secret:cofide/shared/terraform-provider-cofide-gpg-fingerprint-lbsrcV"
          GPG_FINGERPRINT=$(aws secretsmanager get-secret-value \
            --secret-id $GPG_FINGERPRINT_SECRET_ARN \
            --region ${{ secrets.AWS_REGION }} \
            --query 'SecretString' \
            --output text)
          echo "::add-mask::$GPG_FINGERPRINT"
          echo "GPG_FINGERPRINT=$GPG_FINGERPRINT" >> $GITHUB_ENV

          GPG_PASSPHRASE_SECRET_ARN="arn:aws:secretsmanager:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:secret:cofide/shared/terraform-provider-cofide-gpg-passphrase-7FBwwt"
          GPG_PASSPHRASE=$(aws secretsmanager get-secret-value \
            --secret-id $GPG_PASSPHRASE_SECRET_ARN \
            --region ${{ secrets.AWS_REGION }} \
            --query 'SecretString' \
            --output text)
          echo "::add-mask::$GPG_PASSPHRASE"
          echo "GPG_PASSPHRASE=$GPG_PASSPHRASE" >> $GITHUB_ENV

          GPG_PRIVATE_KEY_SECRET_ARN="arn:aws:secretsmanager:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:secret:cofide/shared/terraform-provider-cofide-gpg-private-key-d0AUtD"
          aws secretsmanager get-secret-value \
            --secret-id $GPG_PRIVATE_KEY_SECRET_ARN \
            --query 'SecretString' \
            --output text | base64 --decode | gpg --batch --import
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          args: release --clean
          version: "~> v2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ env.GPG_FINGERPRINT }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
